# Generated by Django 2.1.7 on 2021-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
