# Generated by Django 2.1.7 on 2021-05-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='cityname',
        ),
        migrations.RenameField(
            model_name='lang',
            old_name='lang',
            new_name='mothertongue',
        ),
        migrations.RenameField(
            model_name='religion',
            old_name='rel',
            new_name='religion',
        ),
    ]
