# Generated by Django 2.1.7 on 2021-05-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0002_auto_20210529_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='religion',
            old_name='religion',
            new_name='religioame',
        ),
    ]
