# Generated by Django 2.1.7 on 2021-06-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0003_auto_20210529_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='product_image')),
                ('bride', models.CharField(max_length=20)),
                ('bridegroom', models.CharField(max_length=20)),
                ('story', models.CharField(max_length=200)),
            ],
        ),
    ]
