# Generated by Django 2.1.7 on 2021-06-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectshadi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
